### ISSUE TITLE
this._cancelAllAnimations is not a function.

### ISSUE THREAD

**Issue by tempurai** [rhanb/nativescript-swipe-layout#2] opened 2018-01-15 09:08 UTC
Hi, 

Thank you for this great work.
However, I got 
file:///app/tns_modules/nativescript-swipe-layout/swipe-layout.common.js:104:38: JS ERROR TypeError: this._cancelAllAnimations is not a function. (In 'this._cancelAllAnimations()', 'this._cancelAllAnimations' is undefined)
exceptions when using the plugins.

I search the master branch and no _cancelAllAnimations function/property. Is this a bug?

**Comment by rhanb** [comment] 2018-01-15 09:30
This issue comes from the latest update of {N}, the function doesn't exist anymore on the View api. This issue will be fixed with the issue #1

**Closed as completed** 2018-01-15 09:39 UTC

**Comment by tempurai** [comment] 2018-01-15 09:50
@rhanb after some testing, I found remove this. _cancelAllAnimations() can allow program to run without error. Hope this can be a short term workaround

**Comment by rhanb** [comment] 2018-01-15 09:52
@lincanli the issue is fixed with the latest version `1.0.5` I published 10 min ago, thank you anyway 👍
